# Generated by Django 4.0.5 on 2022-07-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='location_id',
            new_name='location',
        ),
    ]
