# Generated by Django 4.0.5 on 2022-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_id_usermodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
