# Generated by Django 4.0.5 on 2022-07-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_location_remove_adsmodel_author_adsmodel_category_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='LocationModel',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
        migrations.RemoveField(
            model_name='adsmodel',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='adsmodel',
            name='category_id',
        ),
        migrations.AddField(
            model_name='adsmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.usermodel'),
        ),
        migrations.AddField(
            model_name='adsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.categoriesmodel'),
        ),
    ]
