# Generated by Django 4.0.5 on 2022-07-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_location_locationmodel_rename_user_usermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsmodel',
            name='address',
        ),
    ]
